


// ⚠️ AUTOGENERATED! DON'T EDIT FROM HERE... ⚠️
const codepointsMap = {
// TO_BE_REPLACED


	checkbox_check: 				"\f10d",
	chevron_down_alt: 				"\f10c",
	corner_up_left: 				"\f114",
	corner_up_right: 				"\f115",
	chevron_down_alt: 				"\f10c",
	double_corner_up_left:			"\f11a",
	fth_alert_triangle: 			"\f11f",
	fth_arrow_left: 		  		"\f11c",
	fth_arrow_right: 				"\f11d",
	fth_calendar:					"\f126",
	fth_check: 						"\f121",
	fth_chevron_down:				"\f127",
	fth_chevron_left: 				"\f123",
	fth_chevron_right: 				"\f125",
	fth_copy: 						"\f12e",
	fth_download: 					"\f12a",
	fth_edit: 						"\f12d",
	fth_ext_link: 			  		"\f12f",
	fth_file_move: 					"\f131",
	fth_info: 						"\f13f",
	fth_lock: 						"\f141",
	fth_more_horizontal: 			"\f14c",
	fth_more_vertical: 				"\f14a",
	fth_pen_tool:			 		"\f14e",
	fth_repeat: 				  	"\f152",
	fth_share: 						"\f157",
	fth_times: 			  			"\f15b",
	fth_trash: 			  			"\f15f",
	fth_trash_delete:  				"\f15d",
	fth_trash_restore: 	 			"\f15e",
	ius:				 			"\f169",


// TO_BE_REPLACED
};
// ⚠️ ...TO HERE ⚠️

const keyCodeToDecimal = code => parseInt(code.replace("\f", "0xf"), 16);

const codepointsDecimal = Object.keys(codepointsMap).reduce((tot, curr) => {
    tot[curr] = keyCodeToDecimal(codepointsMap[curr]);
    return tot;
}, {});



module.exports = {
	"assetTypes": ['css', 'html'],
	"fontTypes": ['svg', 'ttf', 'woff', 'woff2'],
	"inputDir": "../svg",
	"name": "GFLFontIcon",
	normalize: true,
	"prefix": "gfl",
	"outputDir": "./",
	"codepoints": codepointsDecimal
};
